apiVersion: v1
kind: Service
metadata:
  name: fulltext
  labels:
    app.kubernetes.io/name: fulltext
    app.kubernetes.io/part-of: huly
spec:
  selector:
    app.kubernetes.io/name: fulltext
  ports:
    - name: http
      port: 4700
      targetPort: http
