apiVersion: v1
kind: Service
metadata:
  name: fulltext
  labels:
    {{- include "huly.labels" . | nindent 4 }}
    app: fulltext
spec:
  selector:
    app: fulltext
  ports:
    - name: http
      port: 4700
      targetPort: 4700
