apiVersion: v1
kind: Service
metadata:
  name: transactor
  labels:
    {{- include "huly.labels" . | nindent 4 }}
    app: transactor
spec:
  selector:
    app: transactor
  ports:
    - name: http
      port: 3333
      targetPort: 3333
