{{- if .Values.redpanda.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: redpanda
  labels:
    {{- include "huly.labels" . | nindent 4 }}
    app: redpanda
spec:
  selector:
    app: redpanda
  ports:
    - name: kafka
      port: 9092
      targetPort: 9092
    - name: rpc
      port: 33145
      targetPort: 33145
{{- end }}
