{{- if .Values.cockroach.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: cockroach
  labels:
    {{- include "huly.labels" . | nindent 4 }}
    app: cockroach
spec:
  clusterIP: None
  selector:
    app: cockroach
  ports:
    - name: grpc
      port: 26257
      targetPort: 26257
    - name: http
      port: 8080
      targetPort: 8080
{{- end }}
