apiVersion: apps/v1
kind: Deployment
metadata:
  name: rekoni
  labels:
    {{- include "huly.labels" . | nindent 4 }}
    app: rekoni
spec:
  replicas: {{ .Values.rekoni.replicas }}
  selector:
    matchLabels:
      app: rekoni
  template:
    metadata:
      annotations:
        {{- include "huly.checksumAnnotations" . | nindent 8 }}
      labels:
        {{- include "huly.labels" . | nindent 8 }}
        app: rekoni
    spec:
      {{- include "huly.scheduling" . | nindent 6 }}
      containers:
        - name: rekoni
          image: hardcoreeng/rekoni-service:{{ .Values.hulyVersion }}
          ports:
            - name: http
              containerPort: 4004
          env:
            {{- include "huly.envSecret" (dict "name" "SECRET" "key" "SERVER_SECRET" "root" .) | nindent 12 }}
          readinessProbe:
            tcpSocket:
              port: 4004
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 4004
            initialDelaySeconds: 15
            periodSeconds: 30
          {{- with .Values.rekoni.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
