apiVersion: v1
kind: Service
metadata:
  name: stats
  labels:
    {{- include "huly.labels" . | nindent 4 }}
    app: stats
spec:
  selector:
    app: stats
  ports:
    - name: http
      port: 4900
      targetPort: 4900
