apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cockroach-data
  labels:
    app.kubernetes.io/name: cockroach
    app.kubernetes.io/part-of: huly
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
