apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: workspace
  name: workspace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workspace
  template:
    metadata:
      labels:
        app: workspace
    spec:
      containers:
        - env:
            - name: ACCOUNTS_URL
              value: http://account
            - name: STATS_URL
              value: http://stats
            - name: FULLTEXT_URL
              value: http://fulltext
            - name: TRANSACTOR_URL
              value: http://transactor
            - name: STORAGE_CONFIG
              valueFrom:
                secretKeyRef:
                  name: huly-secret
                  key: STORAGE_CONFIG
            - name: MODEL_ENABLED
              value: '*'
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: huly-secret
                  key: DB_URL
            - name: ACCOUNTS_DB_URL
              valueFrom:
                secretKeyRef:
                  name: huly-secret
                  key: DB_URL
            - name: SERVER_SECRET
              valueFrom:
                secretKeyRef:
                  name: huly-secret
                  key: SERVER_SECRET
            - name: QUEUE_CONFIG
              valueFrom:
                secretKeyRef:
                  name: huly-secret
                  key: QUEUE_CONFIG
          image: hardcoreeng/workspace:v0.7.252
          name: workspace
          resources:
            limits:
              memory: "512M"
      restartPolicy: Always