apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - front/deployment.yaml
  - front/service.yaml
  - account/deployment.yaml
  - account/service.yaml
  - transactor/deployment.yaml
  - transactor/service.yaml
  - collaborator/deployment.yaml
  - collaborator/service.yaml
  - workspace/deployment.yaml
  - fulltext/deployment.yaml
  - fulltext/service.yaml
  - rekoni/deployment.yaml
  - rekoni/service.yaml
  - stats/deployment.yaml
  - stats/service.yaml
