{{- if eq (include "huly.minioEnabled" .) "true" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data
  labels:
    {{- include "huly.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.minio.storageClassName }}
  storageClassName: {{ .Values.minio.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.minio.storage }}
{{- end }}
