apiVersion: v1
kind: Service
metadata:
  name: redpanda
  labels:
    app.kubernetes.io/name: redpanda
    app.kubernetes.io/part-of: huly
spec:
  selector:
    app.kubernetes.io/name: redpanda
  ports:
    - name: kafka
      port: 9092
      targetPort: kafka
    - name: rpc
      port: 33145
      targetPort: rpc
