{{- if and .Values.aibot.enabled .Values.mongodb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    {{- include "huly.labels" . | nindent 4 }}
    app: mongodb
spec:
  clusterIP: None
  selector:
    app: mongodb
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
{{- end }}
