apiVersion: cluster.redpanda.com/v1alpha2
kind: Topic
metadata:
  name: fulltext
spec:
  kafkaApiSpec:
    brokers:
      - "redpanda-0.redpanda.default.svc.cluster.local:9093"
      - "redpanda-1.redpanda.default.svc.cluster.local:9093"
      - "redpanda-2.redpanda.default.svc.cluster.local:9093"
    tls:
      caCertSecretRef:
        name: "redpanda-default-cert"
        key: "ca.crt"
---
apiVersion: cluster.redpanda.com/v1alpha2
kind: Topic
metadata:
  name: process
spec:
  kafkaApiSpec:
    brokers:
      - "redpanda-0.redpanda.default.svc.cluster.local:9093"
      - "redpanda-1.redpanda.default.svc.cluster.local:9093"
      - "redpanda-2.redpanda.default.svc.cluster.local:9093"
    tls:
      caCertSecretRef:
        name: "redpanda-default-cert"
        key: "ca.crt"
---
apiVersion: cluster.redpanda.com/v1alpha2
kind: Topic
metadata:
  name: tx
spec:
  kafkaApiSpec:
    brokers:
      - "redpanda-0.redpanda.default.svc.cluster.local:9093"
      - "redpanda-1.redpanda.default.svc.cluster.local:9093"
      - "redpanda-2.redpanda.default.svc.cluster.local:9093"
    tls:
      caCertSecretRef:
        name: "redpanda-default-cert"
        key: "ca.crt"
---
apiVersion: cluster.redpanda.com/v1alpha2
kind: Topic
metadata:
  name: users
spec:
  kafkaApiSpec:
    brokers:
      - "redpanda-0.redpanda.default.svc.cluster.local:9093"
      - "redpanda-1.redpanda.default.svc.cluster.local:9093"
      - "redpanda-2.redpanda.default.svc.cluster.local:9093"
    tls:
      caCertSecretRef:
        name: "redpanda-default-cert"
        key: "ca.crt"
---
apiVersion: cluster.redpanda.com/v1alpha2
kind: Topic
metadata:
  name: workspace
spec:
  kafkaApiSpec:
    brokers:
      - "redpanda-0.redpanda.default.svc.cluster.local:9093"
      - "redpanda-1.redpanda.default.svc.cluster.local:9093"
      - "redpanda-2.redpanda.default.svc.cluster.local:9093"
    tls:
      caCertSecretRef:
        name: "redpanda-default-cert"
        key: "ca.crt"